-- CHIHIZA Database Schema
-- Unified database for Due Diligence, Financial Model, and Digital Twin

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    code TEXT,
    status TEXT DEFAULT 'draft',
    project_type TEXT DEFAULT 'campestre',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_info (
    project_id INTEGER PRIMARY KEY,
    client TEXT,
    location TEXT,
    municipality TEXT,
    department TEXT,
    country TEXT DEFAULT 'Colombia',
    latitude REAL,
    longitude REAL,
    area_total REAL,
    area_construccion REAL,
    valor_venta REAL,
    precio_m2 REAL,
    currency TEXT DEFAULT 'COP',
    exchange_rate REAL DEFAULT 4200,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS due_diligence (
    project_id INTEGER PRIMARY KEY,
    escritura INTEGER DEFAULT 0,
    tradicion INTEGER DEFAULT 0,
    cadena INTEGER DEFAULT 0,
    cedula_cat INTEGER DEFAULT 0,
    hipotecas INTEGER DEFAULT 0,
    embargos INTEGER DEFAULT 0,
    servidumbres INTEGER DEFAULT 0,
    patrimonio INTEGER DEFAULT 0,
    procesos INTEGER DEFAULT 0,
    abogado TEXT,
    obs_legal TEXT,
    puede_comprar INTEGER DEFAULT 1,
    trato_igual INTEGER DEFAULT 1,
    libertad_capital INTEGER DEFAULT 1,
    proteccion INTEGER DEFAULT 1,
    tipo_compra TEXT,
    visa TEXT,
    representante TEXT,
    pot INTEGER DEFAULT 0,
    uso_suelo INTEGER DEFAULT 0,
    parametros INTEGER DEFAULT 0,
    zona_proteccion INTEGER DEFAULT 0,
    zona_riesgo INTEGER DEFAULT 0,
    uso TEXT,
    altura TEXT,
    retiros REAL DEFAULT 0,
    coef_const REAL DEFAULT 0,
    licencia TEXT,
    area_proteg INTEGER DEFAULT 0,
    restriccion_hidrica INTEGER DEFAULT 0,
    inundacion INTEGER DEFAULT 0,
    deslizamiento INTEGER DEFAULT 0,
    incendio INTEGER DEFAULT 0,
    biodiversidad INTEGER DEFAULT 0,
    clasif_amb TEXT,
    estudios_amb TEXT,
    area_coincide INTEGER DEFAULT 0,
    linderos INTEGER DEFAULT 0,
    coordenadas_of INTEGER DEFAULT 0,
    topografia_ver INTEGER DEFAULT 0,
    catastro_act INTEGER DEFAULT 0,
    matricula TEXT,
    folio TEXT,
    numeracion TEXT,
    obs_catastral TEXT,
    agua INTEGER DEFAULT 0,
    energia INTEGER DEFAULT 0,
    gas INTEGER DEFAULT 0,
    alcantarillado INTEGER DEFAULT 0,
    internet_dd INTEGER DEFAULT 0,
    acceso_pav INTEGER DEFAULT 0,
    acceso_todo INTEGER DEFAULT 0,
    sequia INTEGER DEFAULT 0,
    distancia_ciudad REAL DEFAULT 0,
    tiempo_desplaz TEXT,
    hospital INTEGER DEFAULT 0,
    colegios INTEGER DEFAULT 0,
    supermercados INTEGER DEFAULT 0,
    aeropuerto INTEGER DEFAULT 0,
    precio_m2_comp REAL DEFAULT 0,
    num_comparables INTEGER DEFAULT 0,
    tiempo_venta_comp INTEGER DEFAULT 0,
    tendencia TEXT,
    proyectos_nuevos TEXT,
    demanda TEXT,
    perfil_compradores TEXT,
    obs_mercado TEXT,
    costo_cerramiento REAL DEFAULT 0,
    costo_pozo REAL DEFAULT 0,
    costo_energia_conn REAL DEFAULT 0,
    costo_tierras REAL DEFAULT 0,
    costo_topografia REAL DEFAULT 0,
    costo_licencias REAL DEFAULT 0,
    costo_impuestos REAL DEFAULT 0,
    costo_mantenimiento REAL DEFAULT 0,
    riesgo_ppal TEXT,
    desc_riesgos TEXT,
    score_total INTEGER,
    verdict TEXT,
    dd_date TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS financial_model (
    project_id INTEGER PRIMARY KEY,
    cliente TEXT,
    ubicacion TEXT,
    horizonte INTEGER DEFAULT 18,
    area_terreno_fm REAL DEFAULT 0,
    area_const_fm REAL DEFAULT 0,
    terreno REAL DEFAULT 0,
    imp_transf REAL DEFAULT 0,
    legales REAL DEFAULT 0,
    topografia_fm REAL DEFAULT 0,
    servicios_fm REAL DEFAULT 0,
    otros_terreno REAL DEFAULT 0,
    diseno_arq REAL DEFAULT 0,
    diseno_int REAL DEFAULT 0,
    est_struct REAL DEFAULT 0,
    est_topo REAL DEFAULT 0,
    licencia_fm REAL DEFAULT 0,
    permisos_fm REAL DEFAULT 0,
    construccion REAL DEFAULT 0,
    dir_obra REAL DEFAULT 0,
    gerencia_fm REAL DEFAULT 0,
    contingencia INTEGER DEFAULT 10,
    predial REAL DEFAULT 0,
    mantto REAL DEFAULT 0,
    venta_estimada REAL DEFAULT 0,
    tiempo_venta_fm INTEGER DEFAULT 6,
    comision_venta REAL DEFAULT 3,
    renta_mensual REAL DEFAULT 0,
    meses_renta INTEGER DEFAULT 0,
    fee_disc REAL DEFAULT 0,
    fee_dd REAL DEFAULT 0,
    fee_diseno REAL DEFAULT 0,
    fee_gerencia REAL DEFAULT 0,
    comision_chi REAL DEFAULT 2,
    fee_otros REAL DEFAULT 0,
    inversion_total REAL,
    roi_cliente REAL,
    roi_anual REAL,
    utilidad_cliente REAL,
    ingresos_chihiza REAL,
    fm_date TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS digital_twin (
    project_id INTEGER PRIMARY KEY,
    data TEXT,
    dt_date TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS project_notes (
    project_id INTEGER PRIMARY KEY,
    notes TEXT,
    client_vision TEXT,
    project_refs TEXT,
    restrictions TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS project_tags (
    project_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    PRIMARY KEY (project_id, tag_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
